[package]
name = "sort"
version = "0.1.0"
authors = ["Caleb Boylan <calebboylan@gmail.com>"]

[dependencies]
rand = "0.5.5"

[dev-dependencies]
criterion = "0.1.2"

[[bench]]
name = "insertion"
harness = false

[[bench]]
name = "bubble"
harness = false

[[bench]]
name = "merge"
harness = false
